---
apiVersion: v1
kind: Namespace
metadata:
  name: exo3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo3-deploy
  namespace: exo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exo3
  template:
    metadata:
      labels:
        app: exo3
    spec:
      containers:
      - name: exo3
        image: waed/capge-exo3:1.0.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: exo3-svc
  namespace: exo3
spec:
  type: NodePort
  selector:
    app: exo3
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 5300
    protocol: TCP
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-scaleup
spec:
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exo3-deploy
  targetCPUUtilizationPercentage: 70
