---
apiVersion: v1
kind: Pod
metadata:
  namespace: exo3
  name: mariadb-pod
  labels:
    app: mariadb

spec:
  containers:
  - name: mariadb-container
    image: mariadb:10.6
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "750m"
    env:
    - name: MYSQL_DATABASE_HOST
      value: mariadb
    - name: MYSQL_DATABASE_USER
      value: delpiero
    - name: MYSQL_DATABASE_PASSWORD
      value: juve
    - name: MYSQL_DATABASE_DB
      value: exo3
    volumeMounts:
    - name: mariadb-volume
      mountPath: /var/lib/mysql
  volumes:
  - name: mariadb-volume
    persistentVolumeClaim:
      claimName: mariadb-pvc


---
apiVersion: v1
kind: Service
metadata:
  namespace: exo3
  name: mariadb

spec:
  type: ClusterIP 
  selector:
    app: mariadb
  ports:
  - targetPort: 3306
    port: 3306
    protocol: TCP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi 